### ISSUE TITLE
Unknown file format .img.jpeg_small

### ISSUE THREAD

**Issue by AndrewAnnex** [seignovert/python-opus-seti#2]
seems like the api may have changed, as this query fails with the above exception: opus.api.file('co-iss-n1487299402')

**Comment by seignovert** [comment]
Hi @AndrewAnnex,
I missed your issue (my notifications were disabled for that project :flushed:), sorry about that!

Good catch, this come from the recent reformatting of OPUS API. I will need to update the whole test suite with the new `json` responses. They are cached currently in `tests/api/**.json` to speed up the tests during the dev but I definitively need to regenerate the responses at the beginning of the CI to be sure that it does actually works all the time.

For now I added the new response expected for the image you mention and found an easy fix and push it as `v0.4.2` on PyPI.
